[versions]
agp = "8.12.3"
cameraCore = "1.5.1"
converterGson = "2.9.0"
core = "1.7.0"
credentials = "1.5.0"
espressoIntents = "3.7.0"
facebookAndroidSdk = "18.0.3"
firebaseBom = "33.15.0"
firebaseFirestore = "25.1.4"
glide = "5.0.5"
googleid = "1.1.1"
guava = "33.4.8-android"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.7.0"
appcompat = "1.7.0"
lifecycleCommon = "2.9.4"
litertGpu = "1.4.0"
litertMetadata = "1.4.0"
litertSupport = "1.4.0"
lombok = "1.18.38"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
mockitoCore = "5.20.0"
navigationFragment = "2.9.0"
navigationTesting = "2.9.6"
navigationUi = "2.9.0"
playServicesAuth = "21.3.0"
playServicesBase = "18.9.0"
playServicesTasks = "18.4.0"
realmAndroidLibrary = "10.19.0"
retrofit = "2.9.0"
androidxArchCoreTesting = "2.2.0"
robolectric = "4.16"
fragmentTesting = "1.8.9"

[libraries]
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCoreTesting" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoIntents" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationTesting" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraCore" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
camera-video = { module = "androidx.camera:camera-video", version.ref = "cameraCore" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebookAndroidSdk" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycleCommon" }
litert-gpu = { module = "com.google.ai.edge.litert:litert-gpu", version.ref = "litertGpu" }
litert-metadata = { module = "com.google.ai.edge.litert:litert-metadata", version.ref = "litertMetadata" }
litert-support = { module = "com.google.ai.edge.litert:litert-support", version.ref = "litertSupport" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }


play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesTasks" }
realm-android-library = { module = "io.realm:realm-android-library", version.ref = "realmAndroidLibrary" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
tensorflow-lite-support = { group = "org.tensorflow", name = "tensorflow-lite-support" }
tensorflow-lite-metadata = { group = "org.tensorflow", name = "tensorflow-lite-metadata" }
androidx-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragmentTesting" }


[plugins]
androidx-navigation-safe-args = { id = "androidx.navigation.safeargs", version = "2.9.0" }

secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }

android-application = { id = "com.android.application", version.ref = "agp" }